const URL='https://tqrvnunwqbaivbtapqkm.supabase.co';
const KEY='sb_publishable_BohL_Db4wbIOZAJz8Xfbpg_TNl_AO_u';
const db=supabase.createClient(URL,KEY); let state={track:'single',view:'overview',date:new Date().toISOString().slice(0,10),people:[],entries:[],imports:[],audit:[],user:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(s){let e=$('#toast');e.textContent=s;e.style.display='block';setTimeout(()=>e.style.display='none',3500)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function csv(text){let rows=[],row=[],v='',q=false;for(let i=0;i<text.length;i++){let c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){v+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(v);v=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(v);if(row.some(x=>x.trim()))rows.push(row);row=[];v=''}else v+=c}row.push(v);if(row.some(x=>x.trim()))rows.push(row);return rows}
async function load(){let [p,e,i,a]=await Promise.all([db.from('people').select('*').order('name'),db.from('daily_entries').select('*').eq('work_date',state.date),db.from('import_batches').select('*').order('imported_at',{ascending:false}).limit(100),db.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(100)]);state.people=p.data||[];state.entries=e.data||[];state.imports=i.data||[];state.audit=a.data||[];render()}
function rows(){return state.people.filter(p=>p.default_track===state.track).map(p=>{let list=state.entries.filter(e=>e.person_name===p.name&&e.track===state.track),review=list.reduce((s,x)=>s+x.review_count,0),reported=list.reduce((s,x)=>s+(x.reported_output??x.review_count),0),reject=list.reduce((s,x)=>s+x.rejected_count,0),meeting=list.reduce((s,x)=>s+Number(x.meeting_hours),0),other=list.reduce((s,x)=>s+Number(x.other_non_task_hours),0),hours=Math.max(0,8-meeting-other),target=hours*(state.track==='single'?2:1)*Number(p.ramp_target??1);return{p,review,reported,reject,meeting,other,hours,target,rate:target?review/target:0,reason:list.map(x=>x.no_output_reason).filter(Boolean).join('；')}})}
function render(){$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$$('[data-track]').forEach(b=>b.classList.toggle('active',b.dataset.track===state.track));$('#loginBtn').textContent=state.user?'退出编辑':'编辑登录';if(state.view==='overview')overview();if(state.view==='people')people();if(state.view==='imports')imports();if(state.view==='audit')audit()}
function overview(){let r=rows(),total=r.reduce((s,x)=>s+x.review,0),target=r.reduce((s,x)=>s+x.target,0),reject=r.reduce((s,x)=>s+x.reject,0),warn=r.filter(x=>x.reject>5);$('#view').innerHTML=`<div class="cards"><div class="card"><span>当日审核量</span><b>${total}</b></div><div class="card"><span>有效目标量</span><b>${target.toFixed(1)}</b></div><div class="card"><span>整体达成率</span><b>${target?(total/target*100).toFixed(0):0}%</b></div><div class="card"><span>拒绝量 / 告警人数</span><b class="${warn.length?'red':''}">${reject} / ${warn.length}</b></div></div>${warn.length?`<div class="panel warning"><div class="panelhead"><h2>拒绝量高于 5 条警示</h2><span class="red">需当天复盘</span></div>${warn.map(x=>`<span class="pill bad">${esc(x.p.name)} · ${x.reject} 条</span> `).join('')}</div><br>`:''}<div class="panel"><div class="panelhead"><h2>${state.track==='single'?'单镜头':'多镜头'}人员明细</h2><span>${state.date}</span></div>${r.length?`<table><thead><tr><th>人员</th><th>类型 / 入项</th><th>审核量</th><th>日报量</th><th>有效工时</th><th>目标</th><th>达成</th><th>拒绝</th><th>复盘</th></tr></thead><tbody>${r.map(x=>`<tr><td><b>${esc(x.p.name)}</b></td><td>${esc(x.p.person_type)}<div class="mini">${x.p.joined_on||'-'}</div></td><td>${x.review}</td><td><span class="pill ${x.review!==x.reported?'bad':'good'}">${x.reported}</span></td><td>${x.hours.toFixed(1)}h<div class="mini">会议 ${x.meeting}h / 其他 ${x.other}h</div></td><td>${x.target.toFixed(1)}</td><td class="${x.rate<1?'amber':''}">${(x.rate*100).toFixed(0)}%</td><td class="${x.reject>5?'red':''}">${x.reject}</td><td>${esc(x.reason||'-')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">当天暂无数据。登录后可新增人员并导入 CSV。</div>'}</div>`}
function people(){$('#view').innerHTML=`<div class="panel"><div class="panelhead"><h2>人员配置</h2><span>${state.people.length} 人</span></div>${state.people.length?`<table><thead><tr><th>姓名</th><th>类型</th><th>板块</th><th>入项日期</th><th>爬坡系数</th><th>备注</th></tr></thead><tbody>${state.people.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td>${esc(p.person_type)}</td><td>${p.default_track==='single'?'单镜头':'多镜头'}</td><td>${p.joined_on||'-'}</td><td>${p.ramp_target??1}</td><td>${esc(p.note)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">暂无人员数据</div>'}</div>`}
function imports(){$('#view').innerHTML=`<div class="panel"><div class="panelhead"><h2>不可修改的导入记录</h2><span>${state.imports.length} 批</span></div>${state.imports.length?`<table><thead><tr><th>导入时间</th><th>统计日期</th><th>文件名</th><th>维度</th><th>行数</th></tr></thead><tbody>${state.imports.map(x=>`<tr><td>${new Date(x.imported_at).toLocaleString()}</td><td>${x.work_date}</td><td>${esc(x.file_name)}</td><td>${x.import_mode==='2h'?'2 小时':'全天'}</td><td>${x.row_count}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">暂无导入记录</div>'}</div>`}
function audit(){$('#view').innerHTML=`<div class="panel"><div class="panelhead"><h2>云端操作记录</h2><span>自动保留</span></div>${state.audit.length?`<table><thead><tr><th>时间</th><th>数据表</th><th>操作</th><th>记录编号</th></tr></thead><tbody>${state.audit.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>${esc(x.table_name)}</td><td>${esc(x.action)}</td><td class="mini">${esc(x.record_id||'')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">暂无操作记录</div>'}</div>`}
function needLogin(){if(!state.user){$('#loginDialog').showModal();return false}return true}
async function savePerson(){if(!needLogin())return;let name=$('#pName').value.trim();if(!name)return toast('请输入姓名');let row={name,person_type:$('#pType').value.trim()||'正式',default_track:$('#pTrack').value,joined_on:$('#pDate').value||null,ramp_target:Number($('#pRamp').value)||1,note:$('#pNote').value.trim()};let {error}=await db.from('people').upsert(row,{onConflict:'name'});if(error)return toast('保存失败：'+error.message);$('#personDialog').close();toast('人员信息已保存云端');await load()}
async function doImport(){if(!needLogin())return;let f=$('#csvFile').files[0];if(!f)return toast('请选择 CSV 文件');let rs=csv((await f.text()).replace(/^\uFEFF/,'')),h=rs.shift().map(x=>x.trim()),get=(r,n)=>{let i=h.findIndex(x=>n.includes(x));return i<0?'':r[i].trim()},mode=$('#importMode').value,slot=mode==='2h'?($('#timeSlot').value.trim()||'未填写'):'全天',day=$('#importDate').value;let data=rs.map(r=>{let dir=get(r,['目录','track']),name=get(r,['审核人','姓名','人员','personName']),track=dir.includes('多镜头')?'multi':dir.includes('单镜头')?'single':state.track,review=Number(get(r,['人工审核量','审核量','reviewCount'])||0);return{work_date:day,time_slot:slot,person_name:name,person_type:'待配置',track,directory:dir,review_count:review,approved_count:Number(get(r,['审核通过量','通过量'])||0),rejected_count:Number(get(r,['审核拒绝量','拒绝量'])||0),avg_review_seconds:Number(get(r,['平均审核耗时（不含等待）','平均审核耗时','averageSeconds']).replace(/s$/i,'')||0),reported_output:review}}).filter(x=>x.person_name);if(!data.length)return toast('未识别到有效记录');let {data:batch,error:bErr}=await db.from('import_batches').insert({work_date:day,file_name:f.name,row_count:data.length,import_mode:mode}).select().single();if(bErr)return toast('导入失败：'+bErr.message);data.forEach(x=>x.source_batch_id=batch.id);let uniq=[...new Map(data.map(x=>[x.person_name+'|'+x.track,{name:x.person_name,person_type:'待配置',default_track:x.track,joined_on:day,ramp_target:1}])).values()];for(let p of uniq){await db.from('people').upsert(p,{onConflict:'name',ignoreDuplicates:true})}let {error}=await db.from('daily_entries').insert(data);if(error)return toast('记录写入失败：'+error.message);$('#importDialog').close();toast(`已保存 ${data.length} 条到云端`);state.date=day;$('#date').value=day;await load()}
$$('nav button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});$$('[data-track]').forEach(b=>b.onclick=()=>{state.track=b.dataset.track;render()});$('#date').value=state.date;$('#date').onchange=e=>{state.date=e.target.value;load()};$('#importBtn').onclick=()=>{if(needLogin()){ $('#importDate').value=state.date;$('#importDialog').showModal()}};$('#personBtn').onclick=()=>{if(needLogin())$('#personDialog').showModal()};$('#importMode').onchange=e=>$('#slotLabel').hidden=e.target.value!=='2h';$('#savePerson').onclick=savePerson;$('#doImport').onclick=doImport;$$('dialog .close').forEach(x=>x.onclick=()=>x.closest('dialog').close());$('#sendLink').onclick=async()=>{let email=$('#email').value.trim();if(!email)return;let {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});toast(error?'发送失败：'+error.message:'登录链接已发送，请检查邮箱')};$('#loginBtn').onclick=async()=>{if(state.user){await db.auth.signOut();state.user=null;render();toast('已退出编辑')}else $('#loginDialog').showModal()};db.auth.onAuthStateChange((_e,s)=>{state.user=s?.user||null;render()});db.auth.getSession().then(({data})=>{state.user=data.session?.user||null;load()});db.channel('r2v-live').on('postgres_changes',{event:'*',schema:'public'},()=>load()).subscribe();
